language: java
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
notifications:
  slack:
    rooms:
      -secure: "t6eYvQ7mv8L3M+vCLr7KPaxdkhm+CW7UsCLnesn50YqySDQRFbLl0B04ylAH1iXTOW0J0iBNlRbSxaSqcVTsyyF+heVjutMgoyBIBhP0Ks2P3vykze/XKRdkeFWcEGM0T9KJSb6rajwqQBsSXKRMsEq25LNzuMCJIlVmvusD/cr0x/Wx2uxQ+lyez/t+J980tu5KMv65/fTefNkRUnZe6ilzpXS7mlomMrvHGp/GUnwk52DPDjpmIbKN+uiPf7ZCLxQjffptRrkK1PiW/DFujpSTZyjtizk8hnWhNDgwlyd/fLqdTxVkx1NE7wOr0hlc/m741GeV7U9cte0DG2FlLQ6RFv4NKSFblzE3VqRLL7yl8hmDJ9lUh1Kdf4ZrW5UGPwBdDMkG+92Q1vr5qP/Qyx8veSY5Jouy+krhfTYD+TvQoL1oMePqMEAA1k4SXIq8IaekYiKnpME24wgPE/oNNoGEIZ3Qul9LGV3QXdOYpJqZM0YVn2gj6cf7AUZHVlVVmUZqqQxsOPI6xxTjVdUmEeioJs47JS6OEY9MlveM38rgbQwkiHL8ZOJqp4hvwjEn88KqNoplgXOy1La69RxIkVggC/uSgPpGUpz9yPA7ooce3GUpZRkqqS1nQMLg0CfyHTOoHYuc8PC8ggVwwmyUd1Br+WLzVOSMeNWlzPdTwuE="
    on_success: always
    on_failure: always
    on_pull_requests: always
